version: '{build}'
branches:
  only:
  - master
skip_tags: true
environment:
  matrix:
  - ruby_version: 21
    ruby_dir: 2.1.0
  - ruby_version: 21-x64
    ruby_dir: 2.1.0
  - ruby_version: 22
    ruby_dir: 2.2.0
  - ruby_version: 22-x64
    ruby_dir: 2.2.0
  - ruby_version: 23-x64
    ruby_dir: 2.3.0
install:
- ps: >-
    $env:path = "C:\Ruby" + $env:ruby_version + "\bin;" + $env:path

    $tpath = "C:\Ruby" + $env:ruby_version + "\lib\ruby\" + $env:ruby_dir + "\test"

    if ((test-path $tpath) -eq $True){ rm -recurse -force $tpath }

    gem update --system > $null

    if ((gem query -i test-unit -v ">= 3.0") -eq $False){ gem install test-unit --no-document }
cache:
- C:\Ruby21\lib\ruby\gems\2.1.0
- C:\Ruby21-x64\lib\ruby\gems\2.1.0
- C:\Ruby22\lib\ruby\gems\2.2.0
- C:\Ruby22-x64\lib\ruby\gems\2.2.0
- C:\Ruby22-x64\lib\ruby\gems\2.3.0
build: off
test_script:
- cmd: rake
deploy: off
